name: Build Android Release APK
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
      - name: Install dependencies
        run: npm install
      - name: Prebuild Expo Android
        run: npx expo prebuild --platform android
      - name: Build APK Release
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease --no-daemon
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: InspectorClean-Release-APK
          path: android/app/build/outputs/apk/**/*.apk
          if-no-files-found: error
